import type { Metadata } from "next";
import { NextProvider } from "./providers/NextProvider";
import "./globals.css";
import HeaderNavigation from "./components/HeaderNavigation";
import Player from "./components/Player";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <NextProvider>
        <body className="bg-slate-900 min-h-screen relative">
          <HeaderNavigation />
          {children}
          <Player />
        </body>
      </NextProvider>
    </html>
  );
}
